name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - run: dotnet build --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: latest
      - run: dotnet test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

    steps:
      - run: echo "test"
