name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      BUILD_CONFIG: Release
      NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET env
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.404

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0

      - name: Restore package
      - run: dotnet restore

      - name: Build
        run: dotnet build --configuration $BUILD_CONFIG

      - name: Run tests
        run: dotnet test

      - name: Publish on nuget
        run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
